install: composer install --prefer-source

before_script:
  - echo 'extension = "memcached.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE phpar_test;'
  - psql -c 'CREATE DATABASE phpar_test;' -U postgres

services:
  - mysql
  - postgresql
  - memcache

env: PHPAR_MYSQL=mysql://root@127.0.0.1/phpar_test PHPAR_PGSQL=pgsql://postgres@127.0.0.1/phpar_test

language: php
php:
  - 7.4
  - 8.0

matrix:
  fast_finish: true

script: ./vendor/bin/phpunit --verbose
